export enum TextVariant {
  TINY_REGULAR = 'TINY_REGULAR',
  SMALL_REGULAR = 'SMALL_REGULAR',
  MEDIUM_REGULAR = 'MEDIUM_REGULAR',
  LARGE_REGULAR = 'LARGE_REGULAR',
  EXTRA_LARGE_REGULAR = 'EXTRA_LARGE_REGULAR',
  TINY_BOLD = 'TINY_BOLD',
  SMALL_BOLD = 'SMALL_BOLD',
  MEDIUM_BOLD = 'MEDIUM_BOLD',
  LARGE_BOLD = 'LARGE_BOLD',
  EXTRA_LARGE_BOLD = 'EXTRA_LARGE_BOLD'
}

export type TextTypes = {
  variant: TextVariant
}
